{"SecurityAndAuthenticationService": {
  "createAccessControl":{"endpoint":"/api/v1/access-controls","pathVariable":null,"method":"POST","request":"{targetType:string,targetId:int,permissions:Set<Permissions>}","validation":"{targetType:[\"@NotBlank\"],targetId:[\"@NotNull\"],permissions:[\"@NotEmpty\"]}","response":"AccessControl","description":"Createanaccesscontrol"},
  "updateAccessControl":{"endpoint":"/api/v1/access-controls/{id}","pathVariable":"{id:int}","method":"PUT","request":"{targetType:string,targetId:int,permissions:Set<Permissions>}","validation":"{targetType:[\"@NotBlank\"],targetId:[\"@NotNull\"],permissions:[\"@NotEmpty\"]}","response":"AccessControl","description":"Updateanaccesscontrol"},
  "deleteAccessControl":{"endpoint":"/api/v1/access-controls/{id}","pathVariable":"{id:int}","method":"DELETE","request":null,"validation":null,"response":null,"description":"Deleteanaccesscontrol"},
  "createStaffAccount":{"endpoint":"/api/v1/staff-accounts","pathVariable":null,"method":"POST","request":"{name:string,email:string,password:string,role:string}","validation":"{name:[\"@NotBlank\"],email:[\"@Email\"],password:[\"@NotBlank\"],role:[\"@NotBlank\"]}","response":"StaffAccount","description":"Createastaffaccount"},
  "updateStaffAccount":{"endpoint":"/api/v1/staff-accounts/{id}","pathVariable":"{id:int}","method":"PUT","request":"{name:string,email:string,password:string,role:string}","validation":"{name:[\"@NotBlank\"],email:[\"@Email\"],password:[\"@NotBlank\"],role:[\"@NotBlank\"]}","response":"StaffAccount","description":"Updateastaffaccount"},
  "deleteStaffAccount":{"endpoint":"/api/v1/staff-accounts/{id}","pathVariable":"{id:int}","method":"DELETE","request":null,"validation":null,"response":null,"description":"Deleteastaffaccount"},
  "createAgencyAccount":{"endpoint":"/api/v1/agency-accounts","pathVariable":null,"method":"POST","request":"{name:string,email:string,password:string,role:string}","validation":"{name:[\"@NotBlank\"],email:[\"@Email\"],password:[\"@NotBlank\"],role:[\"@NotBlank\"]}","response":"AgencyAccount","description":"Createanagencyaccount"},
  "updateAgencyAccount":{"endpoint":"/api/v1/agency-accounts/{id}","pathVariable":"{id:int}","method":"PUT","request":"{name:string,email:string,password:string,role:string}","validation":"{name:[\"@NotBlank\"],email:[\"@Email\"],password:[\"@NotBlank\"],role:[\"@NotBlank\"]}","response":"AgencyAccount","description":"Updateanagencyaccount"},
  "deleteAgencyAccount":{"endpoint":"/api/v1/agency-accounts/{id}","pathVariable":"{id:int}","method":"DELETE","request":null,"validation":null,"response":null,"description":"Deleteanagencyaccount"},
  "authenticateUser":{"endpoint":"/api/v1/authenticate","pathVariable":null,"method":"POST","request":"{username:string,password:string,twoFactorAuthentication:boolean}","validation":"{username:[\"@NotBlank\"],password:[\"@NotBlank\"],twoFactorAuthentication:[\"@NotNull\"]}","response":"AuthenticationMethod","description":"Authenticateauser"}
}}